### ISSUE TITLE
Without fragments and EventBus

### ISSUE THREAD

**Issue by nikunjdaga** [thiagokimo/Alexei#5]
Hi ..great library.
I am finding it  difficult to implement your code in an activity without using event bus. It would be great help if you could post the implementation of the color pallete calculus in an activity without using any fragments. Thanks in advance!

**Comment by thiagokimo** [comment]
Hello @nikunjdaga,

I've added an example of Alexei running inside an Activity, without using the EventBus.
I'm going to refactor the example app example and probably the whole library.

Cheers

**Comment by nikunjdaga** [comment]
Thanks man!!
I did the changes for the ColorPalleteCalculus and it worked perfectly!
Also thanks for replying so quickly.

I had another question. How can I select the color from the pallete to use that rgb value somewhere else. One method is to make a bitmap of the container and from that getting the rgb value of the pixel. Can you suggest any other workaround?
Thanks again you have been of great help.

**Comment by thiagokimo** [comment]
The ColorPalleteCalculus returns a list of integers, each one represents a color. You can use any of those directly as a color, like I did [here](https://github.com/thiagokimo/Alexei/blob/master/app/src/main/java/com/kimo/examples/alexei/fragments/ColorPaletteResultsFragment.java#L75).

**Comment by nikunjdaga** [comment]
yeah that would work. thanks
